# Generated by Django 5.0.2 on 2024-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_cover/'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
