# Generated by Django 5.0.2 on 2024-02-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_disliked_options_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='post',
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
