# Generated by Django 5.0.2 on 2024-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_notification_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
