from django.urls import path
from .views import (
    all_posts,
    get_next_posts,
    individual_post,
    retrieve_comments,
    like_post,
    dislike_post,
    edit_post,
    delete_post,
    favotires,
    retrieve_favorite,
    add_to_favorites,
    remove_from_favorites,
    create_comment,
    edit_comment,
    delete_comment,
    like_comment,
    dislike_comment,
    liked,
    liked_posts,
    retrieve_liked_posts,
    liked_comments,
    retrieve_liked_comments,
    notifications,
    retrieve_new_notifications,
    all_notifications,
    retrieve_all_notifications,
)

app_name = 'blog'

# URLs for the blog application
urlpatterns = [
    path('posts/all/', all_posts, name='all_posts'),
    path('posts/next/', get_next_posts, name='get_next_posts'),
    path('posts/<int:post_id>/', individual_post, name='individual_post'),
    path('posts/<int:post_id>/like/', like_post, name='like_post'),
    path('posts/<int:post_id>/dislike/', dislike_post, name='dislike_post'),
    path('posts/<int:post_id>/edit/', edit_post, name='edit_post'),
    path('posts/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('favorites/', favotires, name='favorites'),
    path('favorites/retrieve/', retrieve_favorite, name='retrieve_favorites'),
    path('favorites/add/<int:post_id>/', add_to_favorites, name='add_to_favorites'),
    path('favorites/remove/<int:post_id>/', remove_from_favorites, name='remove_from_favorites'),
    path('posts/<int:post_id>/comments/retrieve/', retrieve_comments, name='retrieve_comments'),
    path('posts/<int:post_id>/comments/create/', create_comment, name='create_comment'),
    path('posts/comments/<int:comment_id>/edit/', edit_comment, name='edit_comment'),
    path('posts/comments/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
    path('posts/comments/<int:comment_id>/like/', like_comment, name='like_comment'),
    path('posts/comments/<int:comment_id>/dislike/', dislike_comment, name='dislike_comment'),
    path('liked/', liked, name='liked'),
    path('liked/posts/', liked_posts, name='liked_posts'),
    path('liked/posts/retrieve/', retrieve_liked_posts, name='retrieve_liked_posts'),
    path('liked/comments/', liked_comments, name='liked_comments'),
    path('liked/comments/retrieve/', retrieve_liked_comments, name='retrieve_liked_comments'),
    path('notifications/', notifications, name='notifications'),
    path('notifications/retrieve/', retrieve_new_notifications, name='retrieve_new_notifications'),
    path('notifications/all/', all_notifications, name='all_notifications'),
    path('notifications/all/retrieve/', retrieve_all_notifications, name='retrieve_all_notifications'),
]
