# Generated by Django 5.0.3 on 2024-03-22 23:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('date_seen', models.DateTimeField(blank=True, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('mode_of_response', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('visit', 'Visit'), ('other', 'Other')], max_length=225, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_of_first_response', models.DateTimeField(blank=True, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('date_of_solution', models.DateTimeField(blank=True, null=True)),
                ('link_to_complaint_doc', models.URLField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_responded', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_seen', to=settings.AUTH_USER_MODEL)),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_solved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
    ]
